export const SAY_HI = 'SAY_HI';
export const FIND_ACTIVITY = 'FIND_ACTIVITY';
export const RANDOM_ACTIVITY = 'RANDOM_ACTIVITY';
export const CLEAR_ACTIVITY = 'CLEAR_ACTIVITY';
export const FIND_ACTIVITY_ERROR = 'FIND_ACTIVITY_ERROR';
export const NIGHT_TOGGLER_ACTIVE = 'NIGHT_TOGGLER_ACTIVE';
export const NIGHT_TOGGLER_INACTIVE = 'NIGHT_TOGGLER_INACTIVE';
